# The k3s configuration file, updated with proper IP/SAN

apiVersion: v1
clusters:
- cluster:
    server: https://192.168.80.2:6443
  name: k3s-cluster
contexts:
- context:
    cluster: k3s-cluster
    user: admin
  name: k3s-context
current-context: k3s-context
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: "YOUR_TOKEN_HERE"
